# -*- coding: utf-8 -*-
"""Telco Customer Churn .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I4kb4l0uISFes82GJP3YeEVd17SkhPY9
"""

import pandas as pd

df = pd.read_csv("/content/Telco Customer Churn.csv")

print(df.shape)
print(df['Churn'].value_counts())

churn_rate = (df['Churn'] == 'Yes').mean()*100
print(churn_rate)

df.groupby('Contract')['Churn'].value_counts(normalize=True)

df.groupby('InternetService')['Churn'].value_counts(normalize=True)

df.to_csv("customer_churn_cleaned.csv",index=False)

## Resources

- The original dataset `Telco Customer Churn.csv` was loaded.
- Initial data exploration was performed by checking the shape of the DataFrame and the value counts of the 'Churn' column.
- The churn rate was calculated.
- Churn rates were analyzed based on 'Contract' type and 'InternetService' type.
- The cleaned data has been exported to `customer_churn_cleaned.csv`.